env:
  global:
    - secure: RzFxb34t6O7cASvJf9tBT809CaycnT030B1pyHaJtPytO+AN0zgEFps3JhfCzuVhzuQ0RGQZ0fRbo8rSGOmF0qaqK533DTsC/Hm+aLT4S0a04GO/E5cA9XorJPKqgVklsIWcd2k5/1HfJQ/Q+n+/QBFeRVz60c/ZxhDPVfAzYBmvSG861rnP0a3P9OycR+faE5/aonD0KZE5adx97M5rDpIO50EEeMkfBlxu1J+MOwbJ8cFmUGHU+FgbHJf5LD6XLoa7lXIaV1p+uEHwLbqxoUXKXI6lAzwFk97Z8+usmBNJ83SEDA7+7tC5P2CQqabi4cM5dV1vX8VNZL8XD5eEFUuN1QKSg7kE+Tr6BwsH14jxt4v6roA/S7xsg02+V6kBVClgF5j+FOUb5ROe48BwSXM/fBzNOe5njKNyu453lihvBK4QVgbTsynRDcASrdEh9hTy1A6Fe5iHzkQKPYGt1yb1WS913R8mTFXx+IWmPbGfCDwUwKA4/1wgLIwM3ZpwBPm2+3tIr+jF46JkXC1z1uBDeZ4juHMXUqnwfBW0WzSOSjbFEqELaIOimCAlU1/qMLKuzN1w6BVlGaVs7ES0fLaisIl8H2smelJIlZsMFeJafVUIKCxjUFRTFQ+DqwEbcq3liNxrXprnGvG3EIKfxqqz5Ty20ncInWEr+i8eEfg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
