env:
  global:
    - secure: lhvb1/vkFFfrEobkZd2Rpj0mgLYlW0W0egIIhzC3yzE1wTQEQA9xi4Q/Pz3GrWPrpLYBxm23rml+GMUnWKEe0YFiEvQ7Fps+qR42lqCCM7h208Jw9mtmKjxe2o5fXHESAZow13QM5DcyCvgq+UZ0exUxVjG41fqtpAQOkNPaoOzujyhX5IzVUgwme/yETfQrF4rZSYfcYMj2GrJKiprDUCDE/7ls0ye6aFP+iuOLbKA5HZCei1nSwaney3oArupuehxU4ND7RVhuAMdIp3gevnHy+dZdh8E8XRlYdKE7fzH8XaeVLc0ABS74vLpu1AtpzSHyqNgUDBnxXai7c2w6tTzE3ogjp/Ma0Ur6TdEIKS45BZzyhAEveLPudU6aymDcGvoZ6Hpx0mcq7JRkZTo131t1ahNvviECBG1H3m/+H8z5kziyUN2zQ4kbh97TDJCXRkLH9aWFEbkK/t1lKR01P7b4dziLrII4BzUZ3McdTLf66/jyMJ8D47uYFsy8S8iJdl2mXzs4m7kS6pgPl+Zb8TpuzcCWqVlCn3kveyAPXBci7bD/rOJDyqM92msez/dAKVcnR4G29tRzQPV6mi8wUS+awi1i0o8rjeJHNEZscBaotA6Xa2hjOdBdXrrUn8rbkSBE76ptzZAsbkNyTXr2lYknYAi5Kvcwh63B8zKfw7I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
