env:
  global:
    - secure: g58oOw6ZkJrX6jtafHOALtuqyqqnqTWtI9nojdgy9wlDjLNUoifC9IFYFBNarQVM12zu6WE7ihVnZwFfXGahN2l5aGiRYfE9aeKi8q+4LZzkGbNb1l2H2pALOSzeEy4xi2hDQakWjyx8phCIYSM3RQ9tUth+HDNg6jahdj+uWRlS52tkMYCbrs34JIqOeoSrMQX+UefSQj2GV0A3jMJ4/fQZLWZYnPzsQGf7z1M+S1JwQJ7QcYjfq+LfYa5t3ZTzkXyT/xb7Y8Bp4fGgtIDMOdqtZdw2Sc+9/DB38Kyyh9DZffIkCaV1MNemRt8UwHU7PK9lpuFQr9tlsQBznywBAsMl7UZBFRTzgqeh1Pp0JueHxKvxFB0kioDYsII89TSy11q59ggdggGwDcoZ974bWCpi8XA4X8VUIyqKUzk6gR5Ahg0O0tzg3llcp8H3T1EBP0cTlvShW3ZKNdI9GtN8ujU6gUjfjKuoAQ4OwJkOSCSH1EH10an9dqnhGbsDXThe6aHuYzzzO8PtcioSs8Pqe7hgF8gy26d9PUBqNBVFrvfcg+ZDsrlvvDiL7rA13Zwt8M6U9XzrcHpTQjDpr6w7tEMA7x+ciwbszKYv6pS5Fn9SLPs40lGYVP/JF4Ol8W8s6YBCcaXcmw4nCWHQHJurDP5Ua3qD9sB6KUXE9ddb2/U=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
