env:
  global:
    - secure: M0SLbM8+ZCfnIT9giZvHzh3mN/BL77kzSJUgJn3/7ev5tpgQxQzds9JZWS/h/wmaOSO+BSpPm4n6gOyFz9k6lSHxNfaS4vL5IXyBe3QSClWg2unF0NUY7SaNblbPDctZM9BwVkX6NrZflquhmYGk+6/C3Yr0nsvlvNQH6wT0AN0ZlfzHQc3tKPMnvhEJV1+wliaMnMI4nDibsfe+i+B5U98lwFj1OVD0wwGffDXSln+19OFUtQB39DtELwN30zoWxBD/1/XWah5mN+5oJHaj0Si9fgPBwU5dYn2spKZ/Wa38VSDXskuyeqEhl2zwQIFYuglNl+v/Wguoenp3XWzcJUet5z/KgWpdDrBk0bDHDT2jh2flMZ6WDPJw0X4Gkjawl/L3d/+ncm7HsKuBZjRk6gobcbehP/RQlimKhlJI4Bd50noYCIxI+bKuDfayt1WEbHrjw1q5iQhLxAl4g6wsP/es/I8gv8HVT4h/ggzdecwkFPxaV7jDOQIfu/ZdGr5apz80rXqHZ/5fgOljn7xgnJoBQMMrZFPGK7SRz3xWNPPyzDV/vkjaK8fuoSj7nxvlPKkt33MrDp+zI4d1iUklEN2J7Yo1K1buSWXMasqQTf3F0v3OZZGA226zS1eXaBGI0xwUK1O6/v63/eGhXhPWJYf9oCmWt/1/vF0dYNNNHE8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
