env:
  global:
    - secure: G9JNzL6o2gHt11KFqO9PR0GJenT2M2R3q6VDVfHKWO1mAwrbwJTnnubRBPls6i5XvL+bgKJoAF0YdNyKavkeq2ghhwbI0gi295Lgi6RLJS9ffoDE//ONQq+NNsMfKj1cM7xgUp2EtqqktvTWcbSsClO9UiG4ovvRlxP2EPOMYhah2GiZ49GK1Cf+G1XhbRJGjuI96mLoUt33/+yt97uT9OjkuYYwQzHFtrYDdJWtifD4CL9eL/0KtVOSb5OQLOPK+30OCR/zFB1VMmf9NgA7+e0WeS5/GHgh/6Grn31XVnlWi8Ft9CBjVvv0XM6ONPFtwrVm15JM3IdSKwgvbmd76ZxmL6nahpSlsUSJ9pUB3MveiOB5TqI/R4UqKh1fbAISxddC+sN/D7oyWs3J3LEGMfvkRcB/9KymPWtAqMUa0CoxWox71LDRXHnhvpQj+LgfVk1R925g+f/YoynU2QX2+OZMgjkDeQOLyKwp0wTFhp3EAzaT2xfsi9hVBag+OT2gyEaGDVOQcO1AXxBUCEKyg/gVctemQ3XGM6NZ31wUe9NCp8SA2P4w1CGPa2OBwDXQJrD/vR0vyPT7iGBm4v/XFax7lbRB2d70maK4DbXrgjdF7PqQ7ECxdFws8WDJqru+edldbjrWjBa1uKj/6j5qPx2wEg2fBtnNj5w3E4aSzJk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
