env:
  global:
    - secure: wc4AZcpskIGP59wNvsYnUYyaKB3c+Xgai/2vjmrWXVFTMxH7zAdf1HOXHIAhWO8FzbyjSbcy1SFyj2S+whT7um1aP5IatceG97AuKP+pRMConW5hxLaJlM12bzm4IXnszw0dhXlBawiBiAlOHpJ2gXVaN5svtzwA/qTm9umaTWwXUGwvzvrpYYZeaHxmL0Ega/G1ScIeaONhyI95RpLRUBfREfz+mF8rbTvK7U8OJr5oNJc2ZRq/+bKzIW+1d7Hpep0ruVXR4NB1lUpwLkViGAFLojpPFq8PxxVjNZMpprC46YYV6oYtjiRchJ8De7c09aQh0GFS8e0KAU+jHIQUrh1dIoDMiI8Br7zjUQmoWth3KR5J6eItG8VQFiOeDNR9FFlceKb1JpynbvWu7955BoTxZk6beTdAKeae/UZx8CHoJdhK+K1FjECSvBAq6IVIiJB6cLbiS6EMVPFzOCxo8/O4sc+CMpIXhys1hZ/eEBBmYRVxzulBS1yjCxA1IBztzwm3vbKQQjEPi37uPGcgDeyf4kTUtLh6kbiGcuaIRw2Gj7DkiBL8rWSLXJGf3EumX736BUybEH/Ot0lh4JvrUokkGAYgipIkffvQzJTdbzo2LI+QCq7+Eb0Dx7btiltO2D/PA3ge8iP0QhoC98RyTfCf6tluE1CtvTKQohqfHZg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
