env:
  global:
    - secure: jPGgZ4pymuC384I+/UVvHxnhiGjViyx7cBW/gyX9qEewXRsp2KnvZTtJ0Vzr94no8bJChKIVXCnn75ZcmuN93cLi/eth1NWTWEwjwLIrQwIatMhVldp0LL3Y9VsDSqHJ+P49vUu39h/kV0KggBLC+JwwAR+WuDP1hMLXqp3/Sn8tSaTyrd3VVAh1lO/4+0Y0EdGmvIKdk5Y4Y7rdGJv0OUHkCH6Tsqnln1vqVObPRFTvQpKKT/mW7zmcsZEkJDlqZRC77D2GSiKQLmSjJy2CKKUSy3B7lG5LUokO6onRijHGgaz3Ccf9UcggO1NgMX39Kgg88+Z9xA4hzdWPea6oMwHZOcNH1UXQSL2Bvjm8wELZzIVUjqO9FzLEhKmhbt8GwJshKEGyK9nwYjl7WevYX85LH9KpwGOV/CCR/NBA4PoMuyitVyi1WekSnNSgo5kUCt8JBspg0pxpwyBOoWnM3pzhRZ2x5W/NtneqpPxAD+9UK1hswpEGYKCoJYn7cdTn/xxjRZmfamXopOjtWibMebcpJEvDXY28LKuZTgsxIZKbNPBysm2n7SEiRdn4P+b4A1NkzYl6Bz9Dz3Jb0f2hgrxm66tLwxZdHZgH3cfnOwvVz0dSUP+CtYAAOJRQZ7H+KG1IzclEnyKK0tlAAokZBo40vz9tA8MoE+YfeFNcvYg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
