env:
  global:
    - secure: fATSiO2zIzEhVQnHh7fvUSqyNCSJ5sY4yAcdHqp6sjW+Nkm+RxDA3OmxEvwg4NBzXyVoHLxLxPJrf5kFv9YLy5sDzTkWYpPJ+X9JrrbOb6LiwdISm80sgxyc0xcFV8h+HxN0kA5yvndW65EQ/I2/BXwEjF4312u25cDKsrIp4dHzvqaG1e20gB3iPRAGL5ojfgbKfR/uHxhzwNXLM2HpMkxnraL21HLkqKN6DlN2Hfgw+2NKzdQu4NqgPCz9sSr2xt2pSLmT2W979tmwGxwb7t0GyrkkxgagA4a+mVHsTAAnCBSLUEvc1Jf29f2TFAYrIdbaaSzvK9ZstRgRoQTtVKHzgEo3Iz5W4PZ+YLVw+dxNzyCghVekSXQzH55sAwcYmMrOuYQAj5rJStqrIgr8SBhSaOnXoQ+lqvEBCJS1M2vL6MQKsZ2/n2nv4gZrfhLWX12Snps5+X4fAswou2PGFkE8oUZtiLmAXYVsYsu8vacgPs9jPSn3Anp+kSO2DDO4vKn+3DZr0KslruBLmMbyk2Fl8hHFmRJN2kiYTaKArCJqfUScKRPwRsswc81w4UwEIEz5MEDvFPxHOPMrKbn4eOvdHracPhRETgCnkLEtQ1UJxfjxLmh6bkV2tetzM5Gp6b1QG16zdzUdYvp6vtZpGJvGaWIJCxqNvEO3ytmfxmA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
