env:
  global:
    - secure: WDjjLZYgAXMgrEk4zypQSDX0HdxKqkVkcY196glu+tNYyHsTsqos+P2zTMylTQ77uYAGtxc1sSAj5ohv/mJAwiDqS/Y7JmSDHpEcu2CIJ0E/5IIbdzAckP+rEjH2O66IrK3WycH92KPkIZu9OtXTHZME6qWgMUfSMJS6lUzNxFE2gEvL0FYMbnDTYooaZAgJJOJlCxVDtgbG5FSd7+6AFEgzzqCPSa2xnS9zkCp0SVrw6tFm2IM1lgU1QVbf1b6O+YI24j7Pp8CtqEjB8mJFqQxVNir5eZ1fCrGq/XJWBYD5gpZpLmOADpJvNRjUYodUvYbheXYrpZqk/xlONnvp7XvC3XPn4sqD27h7EbHNkLxu05uiSmmAVQI38dpNkZWCKvXPaINFu0h2nn+zbOKDC0N8tmAEzG9YhQ+viAeYaYeaHPjRgP477eJwuklld0p8VCSJlngADYlHj4bslrYBAE9ZnDx0zhWeE7IPBrmlLtWJb9TZHDnrQ9hrWCUBj6e0AUo54xMM5PHL6dmRBlLxs4ZWCMgYN8N806QnEOpmiI+LUc6uiowC7ggJgoUblnU1PIoCkwZbcVuq6xkBDUynkRChCGdEZRGp/YdwvkJSpF7Wj3dptilfjrMqeqWiqcXRLbOnN9DuT3Sssp15Ir3fuVugxm/Q9TLC4wBEmXWtqtM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
