env:
  global:
    - secure: B09kwiI5jAmyZxC/3WPHha3PGIBtAzpZcrO/Ws261GvMk9SojiyGGtN6Jq1eod42Dh/XdEUCVhqq0j1N86jrzq11HLKicwHSrBBq9qa/Hhq6zj6DcorB/0dUD2eNjn5L2fNQSVQ6Ap2fDkFEY4vTjNsPR6Dm1Y3DdpyGlkpvL5wREE2ep4wOAxnR0w2VZwApbQwGNhEL/O0HyFnH/yAdTP63gKHfav4j/NfIrw3LY4NWkgwtp2wKysl+8a3xbwQnj8dn3GvnF7viHLYO0HvfQDhww+LhsKwKL0JFmZXQ+o29BuXFImL8h+huo7A7DSwdKls/36E3luRwfS+1AvTa+2ZQDabFXl8eA+9sJT/y8a6d/jdw3ChuQjtACcVhPhTCDxUPRB99+yHAZ+rFptRgOeV0JB4el6J6h8xFVQ1Olk8/Cz5wvA61v4DTfxK1LQj/4bmLlFPrJfH4hBR0flTRXSKTyVH7jHnkLB1UXxDTzaDELQ/K2VjYmJryz+TPDcZuUZiTnWYFVw8Kmb/VeE1GHVdBT2nflyrFQb3Ft32NptmeBA++PK2OLH8hOwnrZeGdp6BbPrccW1c947gZDXtLxI8d1KOp4/6FKnGgB5tewQgFm4wRzWOdzxjmQzgKTK8eNeo2wTpQVm6MSdHj74uhJqn2PcNPaCncul5OawgACh4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
