env:
  global:
    - secure: RScIsIM6Il478em23zYkt8GrfoMB9lTS2cJ+L+BziTcwS+3Th7EDk28R9W5LLmXQPJNQdBPbEKeogC5Qq9CF+eNcvXJ85eqrdw4za4wtivHaQbJKFbWO8s4d83t2m+8q373n1A3611mJR9yW9anL644Fb3Y2KxF50Uvd3gqtGD19Nw/41o5Q8jJ5xKLSwQGGRHudMwq2sRcT35PIaWJRBmLRFilQMDQnrRlppqw9+crwqSxMuqPAVL9T9BfHJnGp9I56dQX/vas1Mti767hN/vrWXvlgy/cxvvaK0HDR5p3VU8O/VjFjQCD9j11hHCoIn9/XfPnHvpYcUg68h8GaWRTqCDqoLtfDex+dTMlwz0McNP94uDlDshxKwlvpfYAVKyajhqhZ5jC2HBQXODZK1AuzI13OX1e62+e5lU2bs45CaQy+V5bnY0HSD4i8mbrAXPPX0KkHkoU6+jrMtjezAv1N7nNwU9e7H4xaxVA+Wp8NDalTtst77ZtynNxltRyvKiYhd7/W+FNHhvmNC2PWD/RWfW/Re1iJJ+UfdxXHSyFvnYYD9JmFkZU2BjDXK+6CLceQxaj2tVuzGo3l9OXKy04Mx1g9q7KEU8JQmEwBX058irfJvIu+DCqfU2dxoRTWbeVZoGot5EXjQ0wRBjDFhm4W4NJYhzawkLQp//F4GAk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
