env:
  global:
    - secure: UOWbAwrqNah38DzrG8FZN4G358R13ykGcHsVaFxUSfsqQYnNmm+8Ik+bkS6i19vR2RXtM+liyLDKE7Mr+kUKabrPznyA3V9sg2AN/PcEtl0SNRA3BOB2O2s67s02ozStwSylH7daxZrSSDpfR6Ur8mIAXmNw0m1kEpn+VTsVhFdWCZQiIz0i//pVAbe2usOPDmHAzQGnS7vMFp6XT7rv5gDH0LBGNshzYeqOqMTW6ZZUe1dJ0j3XzQTszW8j40IiaIr9qAsw/2gNQKaqJx3yhKSUNYAjxQ/Bdp/o7iFGm3HKRR32ZXD0khSucIJIpi9nCZcFvqQuQTjNsUhfTPVXVkhQxYjE+e/7iXbjindn0ksputWVFxGOPPyJ6Gjpt1RumMMTaOlVxBw/RdxGeSGWlsc3D5L2bBa/cXHjZ96Mz3oI97cMw59lWnyPuiuxOXN/ir4fCByrbfEXqhKqgahQLF7KD9cnncmNdjwUNTHazbO2erzxQgqIU1sFJzya7mIEQ5gX+7QxoJmGT21FTM84e43Mh7vcir9STcD53uCwx3Qy4ZzAXhScZ4evzZCg1DXniQzMgUO7NfoSjDzwjZ+52BEUt5AWBOSFRP+GkBcB+kFrqFn9T//7/4asYEDmluiK6nOpik3hp+xvj43ujN3k/3gkE/O1S+FKT3K8Hci0pf0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
