env:
  global:
    - secure: zEEFvZQ9oQolur2p2WK2pS6zVBszR4ZvGY36BM4MJEPl5eiNIONT3ovpOpUGJei8nA5qamj6l2oQkNLiAdvnP4n8gWPwLjvZj9WzBDzyHJiqLiyJJW+64oAf6i7hUBnbH9eg3GXgEHyDYkyn3tEmdQAFOubK8jhy5VAh9rvH1EmT7XDIoUvx4iQg8n5fTF/n9rpf20vVFG2jdP2C7zbROHan7xtLU7eWEaZvnIbFCUg4xK0Bzzrc71m35rCmvmNOnxDGxU13cHPvZRDwp0OPpw4y8b2AeuF5N9/3FhETPbxopCRG6UPgEydWywqJz6lqxP2mkp7eVmMAqCTfv1CRdTaKRMO6oD9s2Cbp0ZHu7rW79PBtRVUXUR90lnri6kBayKtP+rGVOzwQFf1352qyHI8qfoez+Zs2OKcBn0uce1RryMSFjMwmxb9OemK8UsfGEYWr/o0DDHgZ/WEjw7UVCex9i1yen1c2CYtbrWKqfKRA8AidWfrA83bABF1RY/dUJ40zrT4C3aNUjXo/snmMXvazrS7oF+kDfuZdjE4mDVP89aZkzy3Ru4Tx4zN73g9Ur7x7wZDNXYbpsnjVsYuYGqoFYIoXOXaX2GV2mP5goCTSeXUtq95E696BF18XaoG67gxhMbrAze+Hr50KZj4TKKHj+24zGm6JrAfRJg3obJ8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/adaway.github.io_git_AdAway
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
